/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ustb.sei.mde.bxcore.dsl.bXCore.impl;

import edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage;
import edu.ustb.sei.mde.bxcore.dsl.bXCore.CustomizedBiGULDefinition;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.eclipse.xtext.common.types.JvmFormalParameter;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Customized Bi GUL Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.impl.CustomizedBiGULDefinitionImpl#getSourceParams <em>Source Params</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.impl.CustomizedBiGULDefinitionImpl#getViewParams <em>View Params</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.impl.CustomizedBiGULDefinitionImpl#getGet <em>Get</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.impl.CustomizedBiGULDefinitionImpl#getPut <em>Put</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CustomizedBiGULDefinitionImpl extends DefinitionImpl implements CustomizedBiGULDefinition
{
  /**
   * The cached value of the '{@link #getSourceParams() <em>Source Params</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceParams()
   * @generated
   * @ordered
   */
  protected EList<JvmFormalParameter> sourceParams;

  /**
   * The cached value of the '{@link #getViewParams() <em>View Params</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getViewParams()
   * @generated
   * @ordered
   */
  protected EList<JvmFormalParameter> viewParams;

  /**
   * The cached value of the '{@link #getGet() <em>Get</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGet()
   * @generated
   * @ordered
   */
  protected XExpression get;

  /**
   * The cached value of the '{@link #getPut() <em>Put</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPut()
   * @generated
   * @ordered
   */
  protected XExpression put;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CustomizedBiGULDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BXCorePackage.Literals.CUSTOMIZED_BI_GUL_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JvmFormalParameter> getSourceParams()
  {
    if (sourceParams == null)
    {
      sourceParams = new EObjectContainmentEList<JvmFormalParameter>(JvmFormalParameter.class, this, BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__SOURCE_PARAMS);
    }
    return sourceParams;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JvmFormalParameter> getViewParams()
  {
    if (viewParams == null)
    {
      viewParams = new EObjectContainmentEList<JvmFormalParameter>(JvmFormalParameter.class, this, BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__VIEW_PARAMS);
    }
    return viewParams;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public XExpression getGet()
  {
    return get;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGet(XExpression newGet, NotificationChain msgs)
  {
    XExpression oldGet = get;
    get = newGet;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__GET, oldGet, newGet);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGet(XExpression newGet)
  {
    if (newGet != get)
    {
      NotificationChain msgs = null;
      if (get != null)
        msgs = ((InternalEObject)get).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__GET, null, msgs);
      if (newGet != null)
        msgs = ((InternalEObject)newGet).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__GET, null, msgs);
      msgs = basicSetGet(newGet, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__GET, newGet, newGet));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public XExpression getPut()
  {
    return put;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPut(XExpression newPut, NotificationChain msgs)
  {
    XExpression oldPut = put;
    put = newPut;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__PUT, oldPut, newPut);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPut(XExpression newPut)
  {
    if (newPut != put)
    {
      NotificationChain msgs = null;
      if (put != null)
        msgs = ((InternalEObject)put).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__PUT, null, msgs);
      if (newPut != null)
        msgs = ((InternalEObject)newPut).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__PUT, null, msgs);
      msgs = basicSetPut(newPut, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__PUT, newPut, newPut));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__SOURCE_PARAMS:
        return ((InternalEList<?>)getSourceParams()).basicRemove(otherEnd, msgs);
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__VIEW_PARAMS:
        return ((InternalEList<?>)getViewParams()).basicRemove(otherEnd, msgs);
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__GET:
        return basicSetGet(null, msgs);
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__PUT:
        return basicSetPut(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__SOURCE_PARAMS:
        return getSourceParams();
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__VIEW_PARAMS:
        return getViewParams();
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__GET:
        return getGet();
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__PUT:
        return getPut();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__SOURCE_PARAMS:
        getSourceParams().clear();
        getSourceParams().addAll((Collection<? extends JvmFormalParameter>)newValue);
        return;
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__VIEW_PARAMS:
        getViewParams().clear();
        getViewParams().addAll((Collection<? extends JvmFormalParameter>)newValue);
        return;
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__GET:
        setGet((XExpression)newValue);
        return;
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__PUT:
        setPut((XExpression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__SOURCE_PARAMS:
        getSourceParams().clear();
        return;
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__VIEW_PARAMS:
        getViewParams().clear();
        return;
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__GET:
        setGet((XExpression)null);
        return;
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__PUT:
        setPut((XExpression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__SOURCE_PARAMS:
        return sourceParams != null && !sourceParams.isEmpty();
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__VIEW_PARAMS:
        return viewParams != null && !viewParams.isEmpty();
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__GET:
        return get != null;
      case BXCorePackage.CUSTOMIZED_BI_GUL_DEFINITION__PUT:
        return put != null;
    }
    return super.eIsSet(featureID);
  }

} //CustomizedBiGULDefinitionImpl
