/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ustb.sei.mde.bxcore.dsl.bXCore.impl;

import edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage;
import edu.ustb.sei.mde.bxcore.dsl.bXCore.MatchExpression;
import edu.ustb.sei.mde.bxcore.dsl.bXCore.Pattern;
import edu.ustb.sei.mde.bxcore.dsl.bXCore.ValueMapping;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Match Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.impl.MatchExpressionImpl#getPattern <em>Pattern</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.impl.MatchExpressionImpl#getValueMappings <em>Value Mappings</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.impl.MatchExpressionImpl#getThen <em>Then</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.impl.MatchExpressionImpl#getOtherwise <em>Otherwise</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MatchExpressionImpl extends ModificationExpressionImpl implements MatchExpression
{
  /**
   * The cached value of the '{@link #getPattern() <em>Pattern</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPattern()
   * @generated
   * @ordered
   */
  protected Pattern pattern;

  /**
   * The cached value of the '{@link #getValueMappings() <em>Value Mappings</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueMappings()
   * @generated
   * @ordered
   */
  protected EList<ValueMapping> valueMappings;

  /**
   * The cached value of the '{@link #getThen() <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThen()
   * @generated
   * @ordered
   */
  protected XExpression then;

  /**
   * The cached value of the '{@link #getOtherwise() <em>Otherwise</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOtherwise()
   * @generated
   * @ordered
   */
  protected XExpression otherwise;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MatchExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BXCorePackage.Literals.MATCH_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Pattern getPattern()
  {
    return pattern;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPattern(Pattern newPattern, NotificationChain msgs)
  {
    Pattern oldPattern = pattern;
    pattern = newPattern;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BXCorePackage.MATCH_EXPRESSION__PATTERN, oldPattern, newPattern);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPattern(Pattern newPattern)
  {
    if (newPattern != pattern)
    {
      NotificationChain msgs = null;
      if (pattern != null)
        msgs = ((InternalEObject)pattern).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BXCorePackage.MATCH_EXPRESSION__PATTERN, null, msgs);
      if (newPattern != null)
        msgs = ((InternalEObject)newPattern).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BXCorePackage.MATCH_EXPRESSION__PATTERN, null, msgs);
      msgs = basicSetPattern(newPattern, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BXCorePackage.MATCH_EXPRESSION__PATTERN, newPattern, newPattern));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ValueMapping> getValueMappings()
  {
    if (valueMappings == null)
    {
      valueMappings = new EObjectContainmentEList<ValueMapping>(ValueMapping.class, this, BXCorePackage.MATCH_EXPRESSION__VALUE_MAPPINGS);
    }
    return valueMappings;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public XExpression getThen()
  {
    return then;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetThen(XExpression newThen, NotificationChain msgs)
  {
    XExpression oldThen = then;
    then = newThen;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BXCorePackage.MATCH_EXPRESSION__THEN, oldThen, newThen);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setThen(XExpression newThen)
  {
    if (newThen != then)
    {
      NotificationChain msgs = null;
      if (then != null)
        msgs = ((InternalEObject)then).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BXCorePackage.MATCH_EXPRESSION__THEN, null, msgs);
      if (newThen != null)
        msgs = ((InternalEObject)newThen).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BXCorePackage.MATCH_EXPRESSION__THEN, null, msgs);
      msgs = basicSetThen(newThen, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BXCorePackage.MATCH_EXPRESSION__THEN, newThen, newThen));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public XExpression getOtherwise()
  {
    return otherwise;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOtherwise(XExpression newOtherwise, NotificationChain msgs)
  {
    XExpression oldOtherwise = otherwise;
    otherwise = newOtherwise;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BXCorePackage.MATCH_EXPRESSION__OTHERWISE, oldOtherwise, newOtherwise);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOtherwise(XExpression newOtherwise)
  {
    if (newOtherwise != otherwise)
    {
      NotificationChain msgs = null;
      if (otherwise != null)
        msgs = ((InternalEObject)otherwise).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BXCorePackage.MATCH_EXPRESSION__OTHERWISE, null, msgs);
      if (newOtherwise != null)
        msgs = ((InternalEObject)newOtherwise).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BXCorePackage.MATCH_EXPRESSION__OTHERWISE, null, msgs);
      msgs = basicSetOtherwise(newOtherwise, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BXCorePackage.MATCH_EXPRESSION__OTHERWISE, newOtherwise, newOtherwise));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BXCorePackage.MATCH_EXPRESSION__PATTERN:
        return basicSetPattern(null, msgs);
      case BXCorePackage.MATCH_EXPRESSION__VALUE_MAPPINGS:
        return ((InternalEList<?>)getValueMappings()).basicRemove(otherEnd, msgs);
      case BXCorePackage.MATCH_EXPRESSION__THEN:
        return basicSetThen(null, msgs);
      case BXCorePackage.MATCH_EXPRESSION__OTHERWISE:
        return basicSetOtherwise(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BXCorePackage.MATCH_EXPRESSION__PATTERN:
        return getPattern();
      case BXCorePackage.MATCH_EXPRESSION__VALUE_MAPPINGS:
        return getValueMappings();
      case BXCorePackage.MATCH_EXPRESSION__THEN:
        return getThen();
      case BXCorePackage.MATCH_EXPRESSION__OTHERWISE:
        return getOtherwise();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BXCorePackage.MATCH_EXPRESSION__PATTERN:
        setPattern((Pattern)newValue);
        return;
      case BXCorePackage.MATCH_EXPRESSION__VALUE_MAPPINGS:
        getValueMappings().clear();
        getValueMappings().addAll((Collection<? extends ValueMapping>)newValue);
        return;
      case BXCorePackage.MATCH_EXPRESSION__THEN:
        setThen((XExpression)newValue);
        return;
      case BXCorePackage.MATCH_EXPRESSION__OTHERWISE:
        setOtherwise((XExpression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BXCorePackage.MATCH_EXPRESSION__PATTERN:
        setPattern((Pattern)null);
        return;
      case BXCorePackage.MATCH_EXPRESSION__VALUE_MAPPINGS:
        getValueMappings().clear();
        return;
      case BXCorePackage.MATCH_EXPRESSION__THEN:
        setThen((XExpression)null);
        return;
      case BXCorePackage.MATCH_EXPRESSION__OTHERWISE:
        setOtherwise((XExpression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BXCorePackage.MATCH_EXPRESSION__PATTERN:
        return pattern != null;
      case BXCorePackage.MATCH_EXPRESSION__VALUE_MAPPINGS:
        return valueMappings != null && !valueMappings.isEmpty();
      case BXCorePackage.MATCH_EXPRESSION__THEN:
        return then != null;
      case BXCorePackage.MATCH_EXPRESSION__OTHERWISE:
        return otherwise != null;
    }
    return super.eIsSet(featureID);
  }

} //MatchExpressionImpl
