<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Repository" nsURI="http:///repository" nsPrefix="repository">
  <eClassifiers xsi:type="ecore:EClass" name="Subsystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" ordered="false"
        upperBound="-1" eType="#//Class" containment="true" eOpposite="#//Class/parentSubsystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" ordered="false"
        upperBound="-1" eType="#//Relation" containment="true" eOpposite="#//Relation/subsystem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsystem" ordered="false"
        lowerBound="1" eType="#//Subsystem" eOpposite="#//Subsystem/relations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" ordered="false"
        lowerBound="2" upperBound="2" eType="#//Class" eOpposite="#//Class/relations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_deferred" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" ordered="false"
        upperBound="-1" eType="#//Feature" containment="true" eOpposite="#//Feature/theClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentSubsystem" ordered="false"
        lowerBound="1" eType="#//Subsystem" eOpposite="#//Subsystem/classes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsystem" ordered="false"
        lowerBound="1" eType="#//Subsystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" ordered="false"
        upperBound="-1" eType="#//Relation" eOpposite="#//Relation/classes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="theClass" ordered="false"
        lowerBound="1" eType="#//Class" eOpposite="#//Class/features"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1"
        eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Routine" eSuperTypes="#//Feature"/>
</ecore:EPackage>
