/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ustb.sei.mde.bxcore.dsl.bXCore;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Primary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.ContextPrimaryExpression#getSide <em>Side</em>}</li>
 * </ul>
 *
 * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getContextPrimaryExpression()
 * @model
 * @generated
 */
public interface ContextPrimaryExpression extends ContextExpression
{
  /**
   * Returns the value of the '<em><b>Side</b></em>' attribute.
   * The literals are from the enumeration {@link edu.ustb.sei.mde.bxcore.dsl.bXCore.SideEnum}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Side</em>' attribute.
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.SideEnum
   * @see #setSide(SideEnum)
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getContextPrimaryExpression_Side()
   * @model
   * @generated
   */
  SideEnum getSide();

  /**
   * Sets the value of the '{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.ContextPrimaryExpression#getSide <em>Side</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Side</em>' attribute.
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.SideEnum
   * @see #getSide()
   * @generated
   */
  void setSide(SideEnum value);

} // ContextPrimaryExpression
