/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ustb.sei.mde.bxcore.dsl.bXCore;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conversion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.Conversion#getBigul <em>Bigul</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.Conversion#getSource <em>Source</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.Conversion#getView <em>View</em>}</li>
 * </ul>
 *
 * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getConversion()
 * @model
 * @generated
 */
public interface Conversion extends EObject
{
  /**
   * Returns the value of the '<em><b>Bigul</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bigul</em>' containment reference.
   * @see #setBigul(BiGULStatement)
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getConversion_Bigul()
   * @model containment="true"
   * @generated
   */
  BiGULStatement getBigul();

  /**
   * Sets the value of the '{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.Conversion#getBigul <em>Bigul</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bigul</em>' containment reference.
   * @see #getBigul()
   * @generated
   */
  void setBigul(BiGULStatement value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' attribute list.
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getConversion_Source()
   * @model unique="false"
   * @generated
   */
  EList<String> getSource();

  /**
   * Returns the value of the '<em><b>View</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>View</em>' attribute list.
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getConversion_View()
   * @model unique="false"
   * @generated
   */
  EList<String> getView();

} // Conversion
