/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ustb.sei.mde.bxcore.dsl.bXCore;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modification Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getModificationExpression()
 * @model
 * @generated
 */
public interface ModificationExpression extends XExpression
{
} // ModificationExpression
