/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ustb.sei.mde.bxcore.dsl.bXCore;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Navigation Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.NavigationExpression#getHost <em>Host</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.NavigationExpression#getNavOp <em>Nav Op</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.NavigationExpression#getPathName <em>Path Name</em>}</li>
 * </ul>
 *
 * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getNavigationExpression()
 * @model
 * @generated
 */
public interface NavigationExpression extends ContextExpression
{
  /**
   * Returns the value of the '<em><b>Host</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Host</em>' containment reference.
   * @see #setHost(ContextExpression)
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getNavigationExpression_Host()
   * @model containment="true"
   * @generated
   */
  ContextExpression getHost();

  /**
   * Sets the value of the '{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.NavigationExpression#getHost <em>Host</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Host</em>' containment reference.
   * @see #getHost()
   * @generated
   */
  void setHost(ContextExpression value);

  /**
   * Returns the value of the '<em><b>Nav Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nav Op</em>' attribute.
   * @see #setNavOp(String)
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getNavigationExpression_NavOp()
   * @model
   * @generated
   */
  String getNavOp();

  /**
   * Sets the value of the '{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.NavigationExpression#getNavOp <em>Nav Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nav Op</em>' attribute.
   * @see #getNavOp()
   * @generated
   */
  void setNavOp(String value);

  /**
   * Returns the value of the '<em><b>Path Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path Name</em>' attribute.
   * @see #setPathName(String)
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getNavigationExpression_PathName()
   * @model
   * @generated
   */
  String getPathName();

  /**
   * Sets the value of the '{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.NavigationExpression#getPathName <em>Path Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path Name</em>' attribute.
   * @see #getPathName()
   * @generated
   */
  void setPathName(String value);

} // NavigationExpression
